name: Build DiPlay APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 替换掉 android-actions/setup-android@v3，改用预先集成SDK的action
    - name: Setup Android SDK
      uses: malinskiy/action-android@release/0.1.2
      with:
        cmdline-tools-version: "12266719"

    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DiPlay-debug-apk
        path: automotive/build/outputs/apk/debug/DiPlay.apk
